feat: create restfull on spring
AndreyVolokhatyy/java-filmorate pull request #5
Opened 2024-02-19 08:59 UTC by AndreyVolokhatyy

2024-02-19 17:33 UTC, mikita95 approved these changes
Все сделано отлично :) Оставил лишь небольшие замечания

2024-02-19 17:33 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<String, Film> films = new HashMap<>();
Лучше было бы вынести хранение данных в отдельных класс , чтобы разграничить ответственности классов

2024-02-19 17:33 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void start() {}
Этот метод ничего не делает, он не нужен

2024-02-19 19:46 UTC, AndreyVolokhatyy commented
В поставленном задании нет условий на роуты. Конкретно на название, поддерживаемые методы. Отсюда тесты постмана не будут проходить, так как не учитавыют логику приложения.

2024-02-20 09:15 UTC, mikita95 requested changes
Тесты и сборка должны успешно проходить

2024-02-22 18:03 UTC, mikita95 approved these changes
Все сделано отлично :) Можно мержить пул-реквест

2024-02-25 08:58 UTC, merged